Add mulit value secrets
bkkas/helm-charts pull request #15
Opened 2022-11-09 09:01 UTC by tomsolem

2022-11-10 06:21 UTC, ah9828 requested changes

2022-11-10 06:21 UTC, ah9828 commented on ct.yaml
> +helm-extra-args: --timeout 600
```suggestion
helm-extra-args: --timeout 600s
```

2022-11-11 07:40 UTC, tomsolem commented on ct.yaml
> +helm-extra-args: --timeout 600
done

2022-11-15 11:30 UTC, ah9828 approved these changes
LGTM

2022-11-15 14:59 UTC, merged